<?php
// TODO: Archivo publico principal web ...
// *: Importamos el Archivo de inicializacion y configuracion inicial de la aplicacion ...
require_once __DIR__ . '/../src/app/app.php';
// *: Arrancamos la app ...
$app->run();