<?php
// TODO: Archivo de inicializacion y configuracion inicial de la aplicacion La Aplicación, (o Slim\App) es el punto de entrada a su aplicación Slim y se utiliza para registrar las rutas que enlazan con sus devoluciones de llamada o controladores ...
// *: Importamos las classes necesarias ...
use DI\Container;
use Slim\Factory\AppFactory;
use Respect\Validation\Factory;
// *: Importamos el Autoload de las classes ...
require_once __DIR__ . '/../../vendor/autoload.php';
session_start();
//* Container de Slim DI ...
$container = new Container();
$settings = require_once __DIR__ . './config/settings.php';
$settings($container); // ?: Añadimos al contenedor ...
// *: Crear App con la Fabrica Slim ...
AppFactory::setContainer($container); // ?: Añadimos a la aplicacion ...
$app = AppFactory::create(); // ?: Creamos la instancia app ...
// *: Importamos los servicios del contenedor ...
require_once __DIR__ . './config/container.php';
// *: Middlewares aplicacion ...
$middleware = require_once __DIR__ . './config/middleware.php';
$middleware($app);
// *: Fabrica de instancias de las validaciones personalizadas ...
Factory::setDefaultInstance(
    (new Factory())
        ->withRuleNamespace('App\\Validation\\Rules')
        ->withExceptionNamespace('App\\Validation\\Exceptions')
); // ?: Ejecutar regla en la cadena ...
// *: Rutas ...
$routesApp = require_once __DIR__ . './Routes/app.php';
$routesApp($app);
$routesWeb = require_once __DIR__ . '/../resources/Routes/web.php';
$routesWeb($app);