<?php
// TODO: Archivo para añadir middleware a la aplicacion slim ...
// *: Importamos las classes necesarias ...
use Slim\App;
use Slim\Views\TwigMiddleware;
return function (App $app) {
    $container = $app->getContainer();
    $settings = $container->get('settings');
    // *: Middleware de Cookies ...
    $app->add(new \App\Middleware\CookieMiddleware($container)); // ?: Controlamos las cookies ...
    // *: Añadir Twig-View Middleware ...
    $app->add(TwigMiddleware::create($app, $container->get('view')));
    // *: Middleware de Validaciones ...
    $app->add(new \App\Middleware\ValidationErrorsMiddleware($container)); // ?: Controlamos la salida de errores de la validacion ...
    // *: Middleware de Imputs ...
    $app->add(new \App\Middleware\OldinputMiddleware($container)); // ?: Controlamos el valor viejo del imput ...
    // *: Middleware de Csrf ...
    $app->add(new \App\Middleware\CsrfViewMiddleware($container)); // ?: Controlamos el token de los formularios ...
    // *: Añadir CSRF Middleware ...
    $app->add($container->get('csrf'));
    // *: Middleware de Nombre de rutas ...
    $app->add(new \App\Middleware\RoutesNameMiddleware($container)); // ?: Controlamos el token de los formularios ...
    // *: Middleware de Session ...
    $app->add(new \App\Middleware\SessionMiddleware($container)); // ?: Controlamos la sesiones ...
    // *: Middleware de Routes ...
    $app->addRoutingMiddleware();
     // *: Middleware de Errors ...
    $app->addErrorMiddleware(
        $settings['displayErrorDetails'],
        $settings['logErrorDetails'],
        $settings['logErrors']
    ); //?: Convierte la salida de errores ...
};
